### ISSUE TITLE
support for dependencies

### ISSUE THREAD

**Issue by gurpalw** [z0mbix/rolecule#8]
When testing a role that depends on another role, rolecule fails with the below error:

```
 rolecule test -n                                      ✔ │ ▼  x   15:44:34  
   • creating container rolecule-redis_exporter-ubuntu-22.04 with docker
   • converging container rolecule-redis_exporter-ubuntu-22.04 with ansible
ERROR! the role 'docker' was not found in ansible.legacy:/src/tests/roles:/src:/:/src/tests

The error appears to be in '/src/meta/main.yml': line 3, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

dependencies:
  - role: docker
    ^ here
   ⨯ command failed: exit status 1
   • verifying container rolecule-redis_exporter-ubuntu-22.04 with goss (goss.yaml)
Error: found 0 tests, source: tests/goss.yaml
   ⨯ command failed: exit status 78
```

here is my tests/playbook.yml:
```
---
- name: test
  hosts: localhost
  roles:
    - role: .
```

rolecule.yml:

```
---
engine:
  name: docker

provisioner:
  name: ansible

verifier:
  name: goss

instances:
  - name: ubuntu-22.04
    image: ubuntu-systemd:22.04
```

and the `meta/main.yml`:
```
---
dependencies:
  - role: docker
    vars:
      docker:
        network: "{{ redis_exporter.network }}"
```

the `docker` role is on this path `ansible/roles/docker`. along with the `redis_exporter` role: `ansible/roles/redis_exporter`.

Adding support for this would be super useful.

Thank you.
